# -*- coding: utf-8 -*-
"""AI ASS4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HcpkHf05LXUelrGXWIIIxV3jdrvVsNMg
"""

!apt install swi-prolog
!pip install pyswip
import nltk
nltk.download('punkt')
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer
from pyswip import Prolog

inplist = []
f = open("/content/drive/MyDrive/Extra/factbase.txt", 'w')

inp=input('what would you prefer computers or circuit?   ')
words = word_tokenize(inp)
inplist=inplist+words
if "computers"  in inplist or "computer" in inplist or "Computers"  in inplist or "Computer"  in inplist:
    f.write("computers_or_circuits(computers).\n")
elif "circuits"  in inplist or "circuit" in inplist or "Circuits"  in inplist or "Circuit" in inplist:
    f.write("computers_or_circuits(circuits).\n")

inp=input('Do you have extra time to manage? (please reply in yes or no)    ')
words = word_tokenize(inp)
inplist=inplist+words


if "yes" in words or "Yes" in words :
    f.write("extra_time(yes).\n")

elif "no"  in words or "No" in words:
    f.write("extra_time(no).\n")


inp=input('Are you having logical or imaginary thinking?     ')
words = word_tokenize(inp)
inplist=inplist+words

if "logical"  in inplist or "logic" in inplist or "Logical"  in inplist or "Logic" in inplist:
    f.write("logic_or_nonlogic(logic).\n")
elif "imaginary"  in inplist or "image" in inplist or "Imaginary"  in inplist or "Image" in inplist:
    f.write("logic_or_nonlogic(imaginary).\n")


inp=input('Do you like problem solving?(please reply in yes or no)    ')
words = word_tokenize(inp)
inplist+=words

if "yes" in words or "Yes" in words:
    f.write("solving_problems(solving_problems).\n")

elif "no"  in words or "No" in words:
    f.write("solving_problems(no_solving_problems).\n")


inp=input('Do you like number_system?(please reply in yes or no)    ')
words = word_tokenize(inp)
inplist+=words

if "yes" in words or "Yes" in words:
    f.write("number_system(yes).\n")

elif "no"  in words or "No" in words:
    f.write("number_system(no).\n")



inp=input('Do you like maths?(please reply in yes or no)   ')
words = word_tokenize(inp)
inplist+=words

if "yes" in words or "Yes" in words:
    f.write("maths(yes).\n")

elif "no"  in words or "No" in words:
    f.write("maths(no).\n")



inp=input('Do you like probability and stats?(please reply in yes or no)   ')
words = word_tokenize(inp)
inplist+=words

if "yes" in words or "Yes" in words:
    f.write("probability(yes).\n")

elif "no"  in words or "No" in words:
    f.write("probability(no).\n")



inp=input('Do you like discrete maths?(please reply in yes or no)   ')
words = word_tokenize(inp)
inplist+=words

if "yes" in words or "Yes" in words:
    f.write("discrete_maths(yes).\n")

elif "no"  in words or "No" in words:
    f.write("discrete_maths(no).\n")


inp=input('Are you interested in vlsi design?(please reply in yes or no)    ')
words = word_tokenize(inp)
inplist+=words

if "yes" in words or "Yes" in words:
    f.write("vlsi_design(yes).\n")

elif "no"  in words or "No" in words:
    f.write("vlsi_design(no).\n")


inp=input('Do you know about android?(please reply in yes or no)    ')
words = word_tokenize(inp)
inplist+=words

if "yes" in words or "Yes" in words:
    f.write("android(yes).\n")

elif "no"  in words or "No" in words:
    f.write("android(no).\n")



inp=input('Do you interested in information security?(please reply in yes or no)   ')
words = word_tokenize(inp)
inplist+=words
if "yes" in words or "Yes" in words:
    f.write("info_security(yes).\n")

elif "no"  in words or "No" in words:
    f.write("info_security(no).\n")




inp=input('Do you like communication system?(please reply in yes or no)    ')
words = word_tokenize(inp)
inplist+=words
if "yes" in words or "Yes" in words:
    f.write("communication_system(yes).\n")

elif "no"  in words or "No" in words:
    f.write("communication_system(no).\n")


inp=input('Do you like biology?(please reply in yes or no)    ')
words = word_tokenize(inp)
inplist+=words
if "yes" in words or "Yes" in words:
    f.write("biology(yes).\n")

elif "no"  in words or "No" in words:
    f.write("biology(no).\n")


inp=input('Do you like algorithms design?(please reply in yes or no)   ')
words = word_tokenize(inp)
inplist+=words
if "yes" in words or "Yes" in words:
    f.write("algorithm(yes).\n")

elif "no"  in words or "No" in words:
    f.write("algorithm(no).\n")


inp=input('Do you like working on circuits?(please reply in yes or no)    ')
words = word_tokenize(inp)
inplist+=words

if "yes" in words or "Yes" in words:
    f.write("circuits(yes).\n")

elif "no"  in words or "No" in words:
    f.write("circuits(no).\n")

f.close()

swipl = Prolog()
swipl.consult("/content/drive/MyDrive/Extra/ASSIGNMENT_1_PROGRAM.pl")
print("\n\nRecommended Specializations:")
find_specialization = list(swipl.query("find_specialization(Branch)."))

for i in range(0,len(find_specialization)):
  var = find_specialization[i]['Branch'].decode('utf-8')
  print(i+1,' :' ,var)

swipl = Prolog()
swipl.consult("/content/drive/MyDrive/Extra/ASSIGNMENT_1_PROGRAM.pl")
print("\n\nRecommended Specializations:")
find_specialization = list(swipl.query("find_specialization(Branch)."))

for i in range(0,len(find_specialization)):
  var = find_specialization[i]['Branch'].decode('utf-8')
  print(i+1,' :' ,var)

print("Recommended Careers:\n")

for i in range(0,len(find_specialization)):
  var = find_specialization[i]['Branch'].decode('utf-8')
  print(i+1,' :' ,var)
  print('\n')

  
  if(var=='Data Engineering'):
    print('Recommended Branch: Computer Science')
    print('You have experience in details of computers and software works.')
    print('you are logical person. you are also good in probability,problem solving and number_system. You have exprience of computers. So, you can take Data Engineering as the specialization for higher studies.')
    print('The careers that suitable for you are with ranking:')
    print('-1.) DATA SCIENTIST')
    print('-2.) DATA ANALYST')
    print('-3.) DATA RESEARCHER')
    print('-4.) SOFTWARE ENGINEER')
    print('-5.) QUALITY ASSURANCE ENGINEER')



  if( var=="Artificial Intelligence"):
    print('You have experience in details of computers and software works.')
    print('you are logical person.you are also good in discrete maths and problem solving. You have exprience of computers. So, you can take Artificial Intelligence as the specialization for higher studies.')
    print('The careers that suitable for you are with ranking:')
    print('-1.) AI ENGINEER')
    print('-2.) DATA ENGINEER')
    print('-3.) DATA ANALYST')
    print('-4.) NLP ENGINEER')
    print('-5.) DATA RESEARCHER')
    print('-6.) SOFTWARE ENGINEER')
    print('-7.) QUALITY ASSURANCE ENGINEER')

  if(var=="Mobile Computing"):
    print('Recommended Branch: Computer Science')
    print('You have experience in details of computers and software works.')
    print('you have interest in app development and logical_thinking.You have exprience of computers. So you can go for Mobile Computing as a specialization for higher studies.')
    print('The careers that suitable for you are with ranking:')
    print('-1.) GAME DEVELOPMENT')
    print('-2.) MOBILE APP DEVELOPMENT')
    print('-3.) SYSTEM ENGINEER')
    print('-4.) SOFTWARE ENGINEER')
    print('-5.) QUALITY ASSURANCE ENGINEER')


  if(var=="Computer Security"):
    print('Recommended Branch: Computer Science')
    print('You have experience in details of computers and software works.')
    print('you have interest in number system,logical thinking, probability and information security. You have experience of computers as well. So you can go for Computer Security as a specialization for higher studies .')
    print('The careers that suitable for you are with ranking:')
    print('-1.) COMPUTER SECURITY ENGINEER')
    print('-2.) SYSTEM ENGINEER')
    print('-3.) CLOUD SUPPORT ENGINEER')
    print('-4.) INFORMATION SECURITY ENGINEER')
    print('-5.) DATA SECURITY ENGINEER')
    print('-6.) SOFTWARE ENGINEER')
    print('-7.) QUALITY ASSURANCE ENGINEER')




  if(var=="General Specialization"):
    print('Recommended Branch: Computer Science')
    print('You have experience in details of computers and software works.')
    print('you have interest in app development,logical thinking, descrete_maths, solving_problems, number systems and probability.You have exprience of computers. So you can go for without specialization for higher studies.')
    print('The careers that suitable for you are with ranking:')
    print('-1.) AI ENGINEER')
    print('-2.) DATA ENGINEER')
    print('-3.) DATA ANALYST')
    print('-4.) NLP ENGINEER')
    print('-5.) DATA RESEARCHER')
    print('-6.) DATA SCIENTIST')
    print('-7.) COMPUTER SECURITY ENGINEER')
    print('-8.) SYSTEM ENGINEER')
    print('-9.) CLOUD SUPPORT ENGINEER')
    print('-10.) INFORMATION SECURITY ENGINEER')
    print('-11.) DATA SECURITY ENGINEER')
    print('-12.) GAME DEVELOPMENT')
    print('-13.) MOBILE APP DEVELOPMENT')
    print('-14.) SOFTWARE ENGINEER')
    print('-15.) QUALITY ASSURANCE ENGINEER')

  if(var=="Vlsi Design"):
    print('Recommended Branch: Electronics and Communication Engineering')
    print('You have experience in details of CIRCUITS and HARDWARE componenets.')
    print('you have interest in vlsi design and logical thinking. You have experience of circuits as well. So you can go for VLSI Design Flow as a specialization for higher studies.')
    print('The careers that suitable for you are with ranking:')
    print('-1.) EMBEDDING ENGINEER')
    print('-2.) VLSI DESIGN ENGINEER')
    print('-3.) VLSI FLOW ENGINEER')
    print('-4.) QA ENGINEER')
    print('-5.) VLSI DESIGN AND FLOW ENGINEER')
    print('-6.) SYSTEM ENGINEER')

  if(var=="Communication and Programming"):
    print('Recommended Branch: Electronics and Communication Engineering')
    print('You have experience in details of CIRCUITS and HARDWARE componenets.')
    print('you have interest in communication system and logical thinking. You have experience of circuits as well. So you can go for Communication System and programming as a specialization for higher studies.')
    print('The careers that suitable for you are with ranking:')
    print('-1.) EMBEDDING ENGINEER')
    print('-2.) COMMUNICATION ENGINEER')
    print('-3.) RTL DESIGNER')
    print('-4.) GDS ENGINEER')
    print('-5.) SYSTEM ENGINEER')



  if(var=="Computational Biology"):
    print('Recommended Branch: Computational Biology')
    print('You have experience in details of COMPUTERS and BIOLOGY.')
    print('you have interest in number system,biology and algorithm. You have experience of computers as well. So you can go for Computational Biology as a specialization for higher studies.')
    print('The careers that suitable for you are with ranking:')
    print('-1.) COMPUTATIONAL ENGINEER')
    print('-2.) SOFTWARE ENGINEER')
    print('-3.) SYSTEM ENGINEER')


  if(var=='gap'):
    print('Recommendation: Gap Year ')
    print('no database maintained')
    print('Sorry. We cannot help you because you have a variety of traits.')
  

  print('\n')

from google.colab import drive
drive.mount('/content/drive')